version: "3.9"
services:
  easyocr:
    build:
      context: ./easyocr-server
      dockerfile: Dockerfile
    container_name: 'tsr_easyocr'
    hostname: 'tsr_easyocr'
    ports:
      - 8333:8333
    networks:
      - tsr_net

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'tsr_server'
    depends_on:
      - "easyocr"
    ports:
      - 8444:8444
    networks:
      - tsr_net
      
networks:
  tsr_net:
    driver: bridge
